import ApprovalListPage from '../components/ApprovalListPage'

const approvalBoxConfigs = {
  drafts: {
    title: '임시저장함',
    description: '작성 중인 결재 문서를 이어서 작성하거나 삭제할 수 있습니다.',
    dateLabel: '저장일',
    emptyMessage: '임시저장한 문서가 없습니다.',
    statusOptions: ['DRAFT'],
    approvals: [
      {
        approvalId: 94,
        box: 'drafts',
        documentNumber: 'DRAFT-094',
        title: '개발 서버 모니터링 도구 도입 검토',
        writerName: '김관리',
        documentType: '품의서',
        currentStep: null,
        totalSteps: 0,
        displayDate: '2026-07-29 21:14',
        status: 'DRAFT',
      },
      {
        approvalId: 90,
        box: 'drafts',
        documentNumber: 'DRAFT-090',
        title: '하반기 백엔드 교육 과정 신청',
        writerName: '김관리',
        documentType: '교육 신청',
        currentStep: null,
        totalSteps: 0,
        displayDate: '2026-07-28 18:32',
        status: 'DRAFT',
      },
      {
        approvalId: 84,
        box: 'drafts',
        documentNumber: 'DRAFT-084',
        title: '팀 개발 장비 교체 계획',
        writerName: '김관리',
        documentType: '비품 구매',
        currentStep: null,
        totalSteps: 0,
        displayDate: '2026-07-25 13:07',
        status: 'DRAFT',
      },
    ],
  },
  sent: {
    title: '내가 작성한 문서',
    description: '내가 작성하거나 상신한 결재 문서의 진행 상태를 확인합니다.',
    dateLabel: '상신일',
    emptyMessage: '작성한 결재 문서가 없습니다.',
    statusOptions: [
      'DRAFT',
      'IN_PROGRESS',
      'APPROVED',
      'REJECTED',
      'CANCELED',
    ],
    approvals: [
      {
        approvalId: 71,
        box: 'sent',
        documentNumber: 'AP-2026-071',
        title: '개발팀 업무용 노트북 구매 요청',
        writerName: '박준호',
        documentType: '비품 구매',
        currentStep: 1,
        totalSteps: 2,
        displayDate: '2026-07-28 09:42',
        status: 'IN_PROGRESS',
        detailAvailable: true,
      },
      {
        approvalId: 58,
        box: 'sent',
        documentNumber: 'AP-2026-058',
        title: '7월 외근 교통비 정산',
        writerName: '김관리',
        documentType: '비용 정산',
        currentStep: 2,
        totalSteps: 2,
        displayDate: '2026-07-23 14:05',
        status: 'APPROVED',
      },
      {
        approvalId: 49,
        box: 'sent',
        documentNumber: 'AP-2026-049',
        title: '개발 컨퍼런스 참가 신청',
        writerName: '김관리',
        documentType: '교육 신청',
        currentStep: 1,
        totalSteps: 2,
        displayDate: '2026-07-17 10:21',
        status: 'REJECTED',
      },
    ],
  },
  pending: {
    title: '결재 대기함',
    description: '현재 내가 처리해야 하는 결재 문서를 확인합니다.',
    dateLabel: '상신일',
    emptyMessage: '처리할 결재 문서가 없습니다.',
    statusOptions: ['PENDING'],
    approvals: [
      {
        approvalId: 71,
        box: 'pending',
        documentNumber: 'AP-2026-071',
        title: '개발팀 업무용 노트북 구매 요청',
        writerName: '박준호',
        documentType: '비품 구매',
        currentStep: 1,
        totalSteps: 2,
        displayDate: '2026-07-28 09:42',
        status: 'PENDING',
        detailAvailable: true,
      },
      {
        approvalId: 68,
        box: 'pending',
        documentNumber: 'AP-2026-068',
        title: '2026년 하반기 교육비 지원 신청',
        writerName: '이서윤',
        documentType: '교육 신청',
        currentStep: 2,
        totalSteps: 3,
        displayDate: '2026-07-27 16:18',
        status: 'PENDING',
        detailAvailable: true,
      },
      {
        approvalId: 63,
        box: 'pending',
        documentNumber: 'AP-2026-063',
        title: '7월 프로젝트 외근 교통비 정산',
        writerName: '최민호',
        documentType: '비용 정산',
        currentStep: 1,
        totalSteps: 1,
        displayDate: '2026-07-26 11:05',
        status: 'PENDING',
        detailAvailable: true,
      },
    ],
  },
  processed: {
    title: '결재 처리함',
    description: '내가 승인하거나 반려한 결재 문서의 처리 결과를 확인합니다.',
    dateLabel: '처리일',
    emptyMessage: '처리한 결재 문서가 없습니다.',
    statusOptions: ['APPROVED', 'REJECTED'],
    approvals: [
      {
        approvalId: 61,
        box: 'processed',
        documentNumber: 'AP-2026-061',
        title: 'QA 자동화 테스트 도구 구독 연장',
        writerName: '오세진',
        documentType: '품의서',
        currentStep: 2,
        totalSteps: 2,
        displayDate: '2026-07-26 15:42',
        status: 'APPROVED',
      },
      {
        approvalId: 55,
        box: 'processed',
        documentNumber: 'AP-2026-055',
        title: '주말 서버 점검 근무 신청',
        writerName: '정하늘',
        documentType: '근무 신청',
        currentStep: 1,
        totalSteps: 2,
        displayDate: '2026-07-22 17:13',
        status: 'REJECTED',
      },
    ],
  },
  cc: {
    title: '참조 문서함',
    description: '업무 참조자로 지정된 결재 문서와 진행 상태를 확인합니다.',
    dateLabel: '상신일',
    emptyMessage: '참조 중인 결재 문서가 없습니다.',
    statusOptions: ['IN_PROGRESS', 'APPROVED', 'REJECTED'],
    approvals: [
      {
        approvalId: 68,
        box: 'cc',
        documentNumber: 'AP-2026-068',
        title: '2026년 하반기 교육비 지원 신청',
        writerName: '이서윤',
        documentType: '교육 신청',
        currentStep: 2,
        totalSteps: 3,
        displayDate: '2026-07-27 16:18',
        status: 'IN_PROGRESS',
        detailAvailable: true,
      },
      {
        approvalId: 52,
        box: 'cc',
        documentNumber: 'AP-2026-052',
        title: '서비스 정기점검 일정 공유',
        writerName: '김도현',
        documentType: '업무 보고',
        currentStep: 2,
        totalSteps: 2,
        displayDate: '2026-07-20 09:14',
        status: 'APPROVED',
      },
    ],
  },
}

function ApprovalBoxPage({ box }) {
  const config = approvalBoxConfigs[box]

  return <ApprovalListPage {...config} />
}

export default ApprovalBoxPage
